[workspace]
resolver = "2"
members = [
  "crates/zerodb-core",
  "crates/zerodb-io",
  "crates/zerodb",
  "crates/heed-zerodb",
  "crates/zerodb-tools",
  "crates/zerodb-oracle",
]

[workspace.package]
edition = "2021"
rust-version = "1.78"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
memmap2 = "0.9"
libc = "0.2"
thiserror = "1"
crossbeam-utils = "0.8"
proptest = "1"
arbitrary = { version = "1", features = ["derive"] }
criterion = "0.5"
