//! Dual-backend microbenchmark: **zerodb** (the native engine, through the
//! `heed-zerodb` adapter) vs the **Meilisearch LMDB fork** (`heed` =0.22.1),
//! both linked into this one binary via the oracle's existing dual dependency
//! (`heed` + `heed-zerodb`, see this crate's `Cargo.toml`). This is the same
//! two-backends-in-one-process setup the differential fuzzer uses, reused for
//! timing instead of correctness.
//!
//! ## Fair by construction
//! * **Identical operation bodies** — generated by `bench_backend!` over the two
//!   API-identical crate paths, so neither engine gets a hand-written advantage.
//! * **Identical data** — deterministic, seeded (no `rand`, reproducible on any
//!   machine so Graviton runs line up with laptop runs).
//! * **A named database** (`"bench"`) — exactly how milli/hannoy use the store
//!   (their data lives in named DBs, not the unnamed root).
//! * **Identical page size** — LMDB is locked to the OS page size and offers no
//!   selector, so zerodb is pinned to that same value (`page_size(os_page())`).
//!   Without this a 4 KiB-vs-16 KiB geometry gap would swamp the engine
//!   comparison. (A separate run *could* deliberately give zerodb a smaller page
//!   than the OS — that measures a different, production-config question.)
//! * **Matched durability** — the `nosync` groups open both with `NO_SYNC` to
//!   isolate CPU + memcpy + page-cache cost; the `sync` group leaves fsync on to
//!   expose commit/barrier cost.
//!
//! ## Reading the numbers
//! macOS numbers are **indicative**: they isolate the CPU/allocator/memcpy paths
//! and a laptop-SSD fsync. The claim that actually matters — throughput/latency
//! on **linux-aarch64 (Graviton) + EBS gp3**, where a page fault or barrier is a
//! network round-trip — must be run there (PLAN §3 bench lines / the M1.14
//! Graviton-bench remainder). This harness is written to run unchanged on that
//! hardware; only the reported medians move.

use criterion::{black_box, criterion_group, criterion_main, BatchSize, Criterion, Throughput};
use zerodb_oracle::tempdir::TempDir;

/// 1 GiB sparse map — larger than any dataset here, and a multiple of every
/// supported page size (4K/8K/16K/32K/64K) so LMDB's OS-page-multiple rule and
/// zerodb's D-006 check both accept it.
const MAP: usize = 1 << 30;
/// Keys for the put / get / scan groups.
const N: usize = 50_000;
/// Single-put txns for the commit-cost group (each does an fsync in sync mode).
const N_COMMIT: usize = 200;
/// Keys for the overflow group (each value spans > 1 page → overflow pages).
const N_OVF: usize = 2_000;
/// Default inline value size (bytes).
const VAL: usize = 256;

/// splitmix64 — a tiny deterministic PRNG so shuffles are reproducible across
/// platforms without pulling in `rand`.
fn splitmix64(state: &mut u64) -> u64 {
    *state = state.wrapping_add(0x9E37_79B9_7F4A_7C15);
    let mut z = *state;
    z = (z ^ (z >> 30)).wrapping_mul(0xBF58_476D_1CE4_E5B9);
    z = (z ^ (z >> 27)).wrapping_mul(0x94D0_49BB_1331_11EB);
    z ^ (z >> 31)
}

/// `n` ascending 8-byte big-endian keys — the sequential / append-friendly case.
fn ascending_keys(n: usize) -> Vec<Vec<u8>> {
    (0..n as u64).map(|i| i.to_be_bytes().to_vec()).collect()
}

/// The same key set in a deterministic shuffled order (random-insert pattern).
fn shuffled_keys(n: usize, seed: u64) -> Vec<Vec<u8>> {
    let mut keys = ascending_keys(n);
    let mut s = seed;
    for i in (1..keys.len()).rev() {
        let j = (splitmix64(&mut s) % (i as u64 + 1)) as usize;
        keys.swap(i, j);
    }
    keys
}

/// The OS page size (what LMDB is locked to), clamped to zerodb's supported
/// `[4096, 65536]` power-of-two range so zerodb can be pinned to the same value.
fn os_page_size() -> u32 {
    // SAFETY: `sysconf(_SC_PAGESIZE)` is a pure query — no preconditions, no side
    // effects. FFI in the oracle crate is sanctioned by the CLAUDE.md unsafe
    // policy; this is bench-only code.
    let v = unsafe { libc::sysconf(libc::_SC_PAGESIZE) };
    match u32::try_from(v) {
        Ok(p) if (4096..=65536).contains(&p) && p.is_power_of_two() => p,
        _ => 4096,
    }
}

/// Generate one `mod` per backend with an identical op surface. `$setpage`
/// selects whether the engine takes an explicit page size (`set`, zerodb) or
/// uses the OS page size (`noset`, LMDB — it has no selector).
macro_rules! bench_backend {
    ($mod:ident, $heed:ident, $setpage:tt) => {
        mod $mod {
            use $heed::types::Bytes;
            use $heed::{Database, Env, EnvOpenOptions, WithoutTls};

            pub type Db = Database<Bytes, Bytes>;

            pub fn open(
                dir: &std::path::Path,
                map_size: usize,
                no_sync: bool,
                page: u32,
            ) -> Env<WithoutTls> {
                let mut opts = EnvOpenOptions::new().read_txn_without_tls();
                opts.map_size(map_size);
                opts.max_dbs(4);
                bench_backend!(@setpage opts, page, $setpage);
                // SAFETY: single-process, single-threaded, private temp dir; the
                // only flag ever set is NO_SYNC (durability, not a cross-process
                // behavior).
                unsafe {
                    if no_sync {
                        opts.flags($heed::EnvFlags::NO_SYNC);
                    }
                    opts.open(dir)
                }
                .expect("open env")
            }

            pub fn create_db(env: &Env<WithoutTls>) -> Db {
                let mut w = env.write_txn().expect("write_txn");
                let db = env
                    .create_database::<Bytes, Bytes>(&mut w, Some("bench"))
                    .expect("create_database");
                w.commit().expect("commit");
                db
            }

            /// Insert every key in one write txn, then commit (bulk-write shape).
            pub fn bulk_put(env: &Env<WithoutTls>, db: Db, keys: &[Vec<u8>], val: &[u8]) {
                let mut w = env.write_txn().expect("write_txn");
                for k in keys {
                    db.put(&mut w, k.as_slice(), val).expect("put");
                }
                w.commit().expect("commit");
            }

            /// One committed write txn per key — isolates commit / barrier cost.
            pub fn commit_churn(env: &Env<WithoutTls>, db: Db, keys: &[Vec<u8>], val: &[u8]) {
                for k in keys {
                    let mut w = env.write_txn().expect("write_txn");
                    db.put(&mut w, k.as_slice(), val).expect("put");
                    w.commit().expect("commit");
                }
            }

            /// Point lookups; returns the hit count so the reads can't be elided.
            pub fn point_get(env: &Env<WithoutTls>, db: Db, keys: &[Vec<u8>]) -> usize {
                let r = env.read_txn().expect("read_txn");
                let mut hits = 0usize;
                for k in keys {
                    if db.get(&r, k.as_slice()).expect("get").is_some() {
                        hits += 1;
                    }
                }
                hits
            }

            /// Full forward cursor scan; returns the entry count.
            pub fn scan(env: &Env<WithoutTls>, db: Db) -> usize {
                let r = env.read_txn().expect("read_txn");
                let mut n = 0usize;
                for kv in db.iter(&r).expect("iter") {
                    let _ = kv.expect("entry");
                    n += 1;
                }
                n
            }
        }
    };
    (@setpage $opts:ident, $page:ident, set) => {
        $opts.page_size($page);
    };
    (@setpage $opts:ident, $page:ident, noset) => {
        // LMDB derives its page size from the OS; nothing to set.
        let _ = $page;
    };
}

bench_backend!(lmdb, heed, noset);
bench_backend!(zerodb, heed_zerodb, set);

/// Emit both backends' `bench_function`s for a write op that needs a *fresh,
/// empty* env each iteration (so we measure insertion, not overwrite). Env
/// creation is in the untimed `setup`; only the op is timed.
macro_rules! bench_write_both {
    ($group:ident, $page:expr, $no_sync:expr, $op:ident, $keys:expr, $val:expr) => {{
        $group.bench_function("lmdb", |b| {
            b.iter_batched(
                || {
                    let t = TempDir::new().expect("tempdir");
                    let e = lmdb::open(t.path(), MAP, $no_sync, $page);
                    let db = lmdb::create_db(&e);
                    (t, e, db)
                },
                |(t, e, db)| {
                    lmdb::$op(&e, db, $keys, $val);
                    black_box(&e);
                    drop(e); // unmap before the temp dir is removed
                    drop(t);
                },
                BatchSize::PerIteration,
            )
        });
        $group.bench_function("zerodb", |b| {
            b.iter_batched(
                || {
                    let t = TempDir::new().expect("tempdir");
                    let e = zerodb::open(t.path(), MAP, $no_sync, $page);
                    let db = zerodb::create_db(&e);
                    (t, e, db)
                },
                |(t, e, db)| {
                    zerodb::$op(&e, db, $keys, $val);
                    black_box(&e);
                    drop(e);
                    drop(t);
                },
                BatchSize::PerIteration,
            )
        });
    }};
}

fn bench_seq_put(c: &mut Criterion) {
    let keys = ascending_keys(N);
    let val = vec![0xABu8; VAL];
    let page = os_page_size();
    let mut g = c.benchmark_group("seq_put/v256/nosync");
    g.throughput(Throughput::Elements(N as u64));
    bench_write_both!(g, page, true, bulk_put, keys.as_slice(), val.as_slice());
    g.finish();
}

fn bench_rand_put(c: &mut Criterion) {
    let keys = shuffled_keys(N, 0x1234_5678);
    let val = vec![0xABu8; VAL];
    let page = os_page_size();
    let mut g = c.benchmark_group("rand_put/v256/nosync");
    g.throughput(Throughput::Elements(N as u64));
    bench_write_both!(g, page, true, bulk_put, keys.as_slice(), val.as_slice());
    g.finish();
}

fn bench_commit(c: &mut Criterion) {
    let keys = ascending_keys(N_COMMIT);
    let val = vec![0xABu8; VAL];
    let page = os_page_size();
    let mut g = c.benchmark_group("commit_1put_per_txn/v256/sync");
    g.throughput(Throughput::Elements(N_COMMIT as u64));
    // no_sync = false → each commit fsyncs (data + meta barriers).
    bench_write_both!(
        g,
        page,
        false,
        commit_churn,
        keys.as_slice(),
        val.as_slice()
    );
    g.finish();
}

fn bench_overflow_put(c: &mut Criterion) {
    let keys = ascending_keys(N_OVF);
    let page = os_page_size();
    let val = vec![0xCDu8; page as usize * 2]; // > 1 page → overflow pages both engines
    let mut g = c.benchmark_group("overflow_put/v=2xpage/nosync");
    g.throughput(Throughput::Elements(N_OVF as u64));
    bench_write_both!(g, page, true, bulk_put, keys.as_slice(), val.as_slice());
    g.finish();
}

fn bench_get(c: &mut Criterion) {
    let keys = ascending_keys(N);
    let queries = shuffled_keys(N, 0xBEEF_CAFE);
    let val = vec![0xABu8; VAL];
    let page = os_page_size();
    let mut g = c.benchmark_group("get_rand/v256");
    g.throughput(Throughput::Elements(N as u64));
    {
        let t = TempDir::new().expect("tempdir");
        let e = lmdb::open(t.path(), MAP, true, page);
        let db = lmdb::create_db(&e);
        lmdb::bulk_put(&e, db, keys.as_slice(), val.as_slice());
        g.bench_function("lmdb", |b| {
            b.iter(|| black_box(lmdb::point_get(&e, db, &queries)))
        });
    }
    {
        let t = TempDir::new().expect("tempdir");
        let e = zerodb::open(t.path(), MAP, true, page);
        let db = zerodb::create_db(&e);
        zerodb::bulk_put(&e, db, keys.as_slice(), val.as_slice());
        g.bench_function("zerodb", |b| {
            b.iter(|| black_box(zerodb::point_get(&e, db, &queries)))
        });
    }
    g.finish();
}

fn bench_scan(c: &mut Criterion) {
    let keys = ascending_keys(N);
    let val = vec![0xABu8; VAL];
    let page = os_page_size();
    let mut g = c.benchmark_group("scan_all/v256");
    g.throughput(Throughput::Elements(N as u64));
    {
        let t = TempDir::new().expect("tempdir");
        let e = lmdb::open(t.path(), MAP, true, page);
        let db = lmdb::create_db(&e);
        lmdb::bulk_put(&e, db, keys.as_slice(), val.as_slice());
        g.bench_function("lmdb", |b| b.iter(|| black_box(lmdb::scan(&e, db))));
    }
    {
        let t = TempDir::new().expect("tempdir");
        let e = zerodb::open(t.path(), MAP, true, page);
        let db = zerodb::create_db(&e);
        zerodb::bulk_put(&e, db, keys.as_slice(), val.as_slice());
        g.bench_function("zerodb", |b| b.iter(|| black_box(zerodb::scan(&e, db))));
    }
    g.finish();
}

criterion_group!(
    benches,
    bench_seq_put,
    bench_rand_put,
    bench_commit,
    bench_overflow_put,
    bench_get,
    bench_scan,
);
criterion_main!(benches);
